import { Product } from './types';

export const products: Product[] = [
  {
    id: 'shakti-dhoop-cup',
    name: 'Shree Narayani Vedica Shakti Dhoop Cup',
    nameHi: 'श्री नारायणी वेदिका शक्ति धूप कप',
    description: 'Experience the transformative power of ancient botanical wisdom. Hand-crafted with 108 sacred herbs to manifest victory and protection in your sanctum.',
    descriptionHi: 'प्राचीन वनस्पति विज्ञान की परिवर्तनकारी शक्ति का अनुभव करें। आपके मंदिर में विजय और सुरक्षा का संचार करने के लिए 108 पवित्र जड़ी-बूटियों से हस्तनिर्मित।',
    price: 599,
    originalPrice: 850,
    size: 'Pack of 12 Cups',
    sizeHi: '12 कप का पैक',
    category: 'dhoop',
    categoryHi: 'शक्ति धूप',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBhBrh-My3za2B0pdUo9JQYnd-ulEvuuMbnHDGreqX1x7mCIDWF91aLa1QDda41dS8Fl7j6h5IQOc269Q1tKetReMODhF0lSIXFu9n7iHHdzOaIKX-S5dVRj9nyBiM3gQ2nT-ozituxntQa5pl8An8YozkFEr8Q9sO6GFUfabOJODn-_xxO10S6X6n3-cSuuJC3NY71doBWENJ0DFMDX94BzMMpRrVs6qbYefoxGVtCt_IWR1_WC-2nw6BnMO-moLxBPF6eIj4RFwpl',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAhULc0kZtBmyxmhR3aRSiD6Fy8G9gvv-AUG-SdunBpoY_xjN5JAwwgCvx5KYKAIsdeJgX1jvHqHnQWJKivn6YHaRUC4zPMz58hIpuOSBA0-VVKoMFByByW1uiqA_gRjBa1MgBqNc75czcFKTUrt4FKOBp4To44A9xTRWR4a1szTh6OBa32fOVXNEaQpynJhHW69yxyKiEzACaOJB09m4iSDaeNiRVfPv0crDAaFDgBHyRNE2e5ckpxIRUUSncN8e4ehl5TWlNXgiMK',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCLdFWne3bdxcmR9k7qWTg4XiIdaTj1gFtSJ4LEqSmP3_URh6Xkqnz_rXmoRtHGqnqx209SkUX482T56n9GMYqJuMzybssW8FGWS6wR-TCmRH7zYJkw3LjA2xmZdEKtOVo38R5KiaUn6hpmXFh3LaIMXmWCQ1LzOPTV-xGBB5YWeLVJPf-3v8wykiaEBNK1x591PMElYMU_wS65ZUl1o2rzCNxlnfZm2JySH1_m3XR2X6oVVK2Ru2Sfbx1RJWXdldCHMyx_gticDeIQ',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuD8aNgz5bGURtfeicm3T7W6CqN0CIdzzyNHkgjS1w32Lo34vksmmF7gCSl8fmykvGuzpx69c5OZ3XY2GTtQCq8PVNW4qxF5mMQCGc-6RUt_Ngc_A50cAn-jlDbF452DQk-rt0SpBiBl_jYiuIYteEELOjsJ1gTmsm6nhQ-Es8tWmTE3ChPtNcJ6gJ5hltTCQijHz-00FQ4QHGt6jVT7ErvdELvp9e3l_d5n3tjdEUn4vr38weFA84NnGYlvI5rSQNE-VVyD7e9gWvFo'
    ],
    isFeatured: true
  },
  {
    id: 'maha-shakti-dhoop',
    name: 'Maha Shakti Resin Dhoop',
    nameHi: 'महा शक्ति रेज़िन धूप',
    description: 'A luxurious concentration of natural Guggul, Loban and aromatic wood shreds. Purifies atmospheric dust and fills space with standard Vedic temple resonances.',
    descriptionHi: 'प्राकृतिक गुग्गुल, लोबान और सुगंधित लकड़ी के कतरनों का एक शानदार मिश्रण। वायुमंडलीय धूल को शुद्ध करता है और स्थान को सुंदर और दिव्य सुगंध से भरता है।',
    price: 1250,
    originalPrice: 1500,
    size: '200g Jar',
    sizeHi: '200 ग्राम जार',
    category: 'dhoop',
    categoryHi: 'शक्ति धूप',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDcfpDO39XGL4YyJz7kB1jywMJbEiG4LQbkBOtaAKivvvAHsiqF5Po3THJVOR1wHbXruyF50d7gDUOyEG9qsTXO34WfAc8G_87JtmoYj8AY9bMKMjqe1RKIHZPgTSF7xelSKR99z9R_SVle3EgW9LSbD2A4YB1HBHIu8RvlDy1fFoz9NyjNMe9WtFpnGogN06xO2GPxHtWd_qiA1qaKNTnIS1NLPiKtPdfBL9xcO1gQnb5xTPBW_X3LhwHnUPQbdG0kNgXhqjScVNWf'
    ],
    isFeatured: true
  },
  {
    id: 'pure-sandalwood',
    name: 'Pure Sandalwood Classic',
    nameHi: 'शुद्ध चंदन क्लासिक',
    description: 'Gold-standard classical Sandalwood Agarbatti rolled with natural oils and organic binders. Delivers a soft, meditative woody scent that lingers elegantly.',
    descriptionHi: 'प्राकृतिक तेलों और जैविक बाइंडरों के साथ तैयार की गई सोने के मानक वाली शास्त्रीय चंदन की अगरबत्ती। एक शांत, ध्यानयुक्त सुगंध प्रदान करती है।',
    price: 450,
    originalPrice: 550,
    size: '100g Pack',
    sizeHi: '100 ग्राम पैक',
    category: 'agarbatti',
    categoryHi: 'प्रीमियम अगरबत्ती',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuC6A8ml0PFOiv28XQfxC2I1W-0c37CKkNkiV4XKjG8ctup7Im9TTw6NxV8Zauw8F9W5SVd1zaX05JOfn4OZtqDx3lHhgJltWu2mZ9FjbhY7cApLGgFynnYSJUmrUMmkYE7h6a2o4jL7caWPkXQ797Fq24ZW2rHW03n63QYw08GHRN9InJZBfRFI1nVooxwRbqjztX566rF5-a7aFg6wCArxOfEDazENcrB_Wu6sPGChO04XPy4L48pyqT83n1G3Kxq76Rmf9eORYZrp'
    ]
  },
  {
    id: 'agnihotra-blend',
    name: 'Agnihotra Sacred Blend',
    nameHi: 'अग्निहोत्र पावन मिश्रण',
    description: 'Vedic Havan Samagri formulated with 42 traditional herbs, dried flowers, and forest resins. Ideal for purification fire rituals (Havan / Yajna).',
    descriptionHi: '42 पारंपरिक जड़ी-बूटियों, सूखे फूलों और जंगली राल से बनी वैदिक हवन सामग्री। शुद्धिकरण अग्नि अनुष्ठानों (हवन/यज्ञ) के लिए सर्वोत्तम।',
    price: 890,
    originalPrice: 1100,
    size: '500g Box',
    sizeHi: '500 ग्राम बॉक्स',
    category: 'havan',
    categoryHi: 'पारंपरिक हवन सामग्री',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCtvJkktzfZxLUVMbbHQwZlOnp6Yl65pqFJ0XhJYajzlaXq8ylj_K5LrKNWyUJMGJwm1IW3-GE519HhwBUEz8tdQOAc__y7itqIIjchyMThQKxTopxUCwvNgsOmDxv2tNFCOIAT25yGw7i4YTMl5YDoyBiMD5I8bn0Cy_u_oBCHb1mdu01EDVvqHl6Vuy2Y6eiK6JcugoUVaSb3kUvE-pwkNRRqCONv3ql2Ft_ulVZ0LhxdeiRqkyTj-0SHFlJXZEvgE4bdBnYVb5EC'
    ]
  },
  {
    id: 'jasmine-eternal',
    name: 'Jasmine Eternal Glow',
    nameHi: 'चमेली शाश्वत चमक',
    description: 'Charcoal-free organic dhoop cones infused with authentic night-blooming jasmine extracts. Calming, refreshing, and entirely non-toxic experience.',
    descriptionHi: 'रात की सुगंधित असली चमेली के अर्क से युक्त कोयला-मुक्त जैविक धूप शंकु (कोन)। तनाव दूर करने और मन को शांति देने वाली सुगंध।',
    price: 320,
    originalPrice: 400,
    size: '40 Cones',
    sizeHi: '40 कोन्स',
    category: 'dhoop',
    categoryHi: 'धूप कोन्स',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAH6Y_ppFsc9pEUeIZ9b1UEjJwGLmA6K1DTt7ZRfhcYE1RibXDeFpEP3gxqejhCf-v6CbQU-7x-Z_AoKkRvdUfu_0ps-Nn22WW6Ep2CHVpbmDiv7qxFLj9EQJ5J_mbpzVKynB8r5bTRJFRkHWUJFV0aNHsdZE0Nz5NxU-WzreGbrtkFhjW6mHOa0XmQbw_w1sgt1QyPlzOTt36kpW3vG0TRwGkIVG6BTGgrDoNGcktflNajfMfUNheTq-sJ5gQ52s-yJuRGfgXPqvJN'
    ]
  },
  {
    id: 'royal-kesari',
    name: 'Royal Kesari Saffron',
    nameHi: 'शाही केसरी केसर',
    description: 'Immersive premium incense sticks infused with handpicked organic saffron threads and warm sandalwood resins. Designed for noble, royal sensory guidance.',
    descriptionHi: 'चुनिंदा जैविक केसर के धागों और गर्म चंदन के अर्क से युक्त सुंदर अगरबत्ती। समृद्ध और विलासी संवेदी अनुभव के लिए डिज़ाइन किया गया।',
    price: 1400,
    originalPrice: 1800,
    size: '100g Premium Box',
    sizeHi: '100 ग्राम प्रीमियम बॉक्स',
    category: 'agarbatti',
    categoryHi: 'प्रीमियम अगरबत्ती',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBgaPj4Dh5Ug3KxO4L_LQ2HouncCgpICt5BujUe0d2ZFAZlDrsAUaTPUUGBW7IdnMRa6sQrLJJq08du5alFO5a8IYbynXWE2-adR0dw4-oVagPpc7EU6F1jrtrih-kuzdLuAVktA2f8AJDW0sNPya1dC3Wdwsr-T4uUVct8jPbqxxI3TXtsp2z0S6EwfzeWPIRLasdGYRgOxOcry7efwJIdfEAGzkgP2LWnNe8t5t9NKvE8cZPr5L5wAxdDKLfqPUEhrXlSSbhgGjac'
    ]
  }
];

export const translations: Record<string, Record<string, string>> = {
  en: {
    brandName: 'SHREE NARAYANI VEDICA',
    slogan: 'The Tree of Victory & Protection',
    home: 'Home',
    shop: 'Shop',
    spiritualDhoop: 'Spiritual Dhoop',
    havanSamagri: 'Havan Samagri',
    mantraText: '"Shami shamayate papam, Shami shatruvinashini."',
    mantraCaption: '— Ancient Vedic Chant',
    heroSubtitle: 'Sacred Offerings',
    heroTitle: 'Shree Narayani Vedica',
    heroTitleItalic: 'Shakti Dhoop Cup',
    heroDesc: 'Experience the transformative power of ancient botanical wisdom. Hand-crafted with 108 sacred herbs to manifest victory and protection in your sanctum.',
    shopTheRitual: 'Shop The Ritual',
    ourStory: 'Our Story',
    storyTitle: 'The Story of the Sacred Tree',
    storyIntro: 'Est. Ancient Wisdom',
    storyDesc1: 'Legend has it that the Shami tree (Prosopis cineraria) provided shelter to the Pandavas during their exile. At SHREE NARAYANI VEDICA, we celebrate this enduring symbol of resilience, victory, and protection. Our mission is to bottle the very essence of this sacred lineage, bringing the temple\'s sanctity into the modern home.',
    storyDesc2: 'Every product we create is a testament to the quiet luxury of the sacred—uncompromising in quality, deep in heritage, and divine in its fragrance.',
    storyButton: 'Read Our Full Philosophy',
    collectionTitle: 'Our Sacred Collection',
    collectionSubtitle: 'Curation of heritage-rich spiritual essentials.',
    newsletterTitle: 'Join Our Sacred Circle',
    newsletterSubtitle: 'Receive weekly meditations and early access to limited edition spiritual collection drops.',
    emailPlaceholder: 'ritual@sacred.com',
    subscribe: 'Subscribe',
    footerConcept: 'The Quiet Luxury of the Sacred.',
    allProducts: 'All Products',
    shaktiDhoopCat: 'Shakti Dhoop',
    premiumAgarbattiCat: 'Premium Agarbatti',
    traditionalHavanCat: 'Havan Samagri',
    featuredTag: 'Featured',
    addToCart: 'Add to Cart',
    buyNow: 'Buy Now',
    selectSize: 'Select Size',
    priceSymbol: '₹',
    quantity: 'Quantity',
    packOf12: 'Pack of 12 Cups',
    naturalIngredients: '100% Natural Ingredients',
    ritualReady: 'Purification Ritual Ready',
    burnDuration: '45-Min Burn Duration',
    authenticHeritage: 'Authentic Heritage Blend',
    ritualTitle: 'The Ritual Experience',
    ritualSubtitle: 'Awaken the senses and cleanse the spirit through a structured performance of ancient spiritual hygiene.',
    ritualStep1Title: '01. Cleansing',
    ritualStep1Desc: 'Place the Vedica Shakti cup in a non-flammable burner. Light the rim until it glows red, then blow out the flame to allow the sacred smoke to emerge.',
    ritualStep2Title: '02. Invocation',
    ritualStep2Desc: 'As the smoke fills the room, recite the Shami Mantra to invoke victory and protection over your household and intentions.',
    ritualStep3Title: '03. Diffusion',
    ritualStep3Desc: 'Move the burner clockwise through every corner of your space. The sacred ingredients will neutralize negative energy and leave a lingering scent of serenity.',
    sacredIngredientsTitle: 'Sacred Ingredients',
    ingredient1Title: 'Guggul & Loban',
    ingredient1Desc: 'Sourced from the heart of the forests, these resins are known for their powerful antimicrobial properties and air-purifying qualities.',
    ingredient2Title: 'Desi Cow Dung',
    ingredient2Desc: 'The base of each cup is pure Desi Cow dung, a fundamental element in Vedic havans believed to balance environmental vibrations.',
    ingredient3Title: 'Ayurvedic Herbs',
    ingredient3Desc: 'A proprietary blend of 12 rare herbs that aid in stress reduction, mental clarity, and focus during meditation.',
    victorySlogan: 'विजय और सुरक्षा का वृक्ष',
    shamiVictoryBox: 'The Shami Victory Box',
    shamiVictoryDesc: 'A curated selection of our finest dhoop and samagri, packaged in a sustainable handcrafted wooden vault. The ultimate gift for spiritual elevation.',
    bespokeExperience: 'Bespoke Experience',
    heritageSeries: 'Heritage Series',
    artisanalDhoopbatti: 'Artisanal Dhoopbatti',
  },
  hi: {
    brandName: 'श्री नारायणी वेदिका',
    slogan: 'विजय और सुरक्षा का वृक्ष',
    home: 'होम',
    shop: 'दुकान',
    spiritualDhoop: 'आध्यात्मिक धूप',
    havanSamagri: 'हवन सामग्री',
    mantraText: '"शमी शमयते पापम्, शमी शत्रुविनाशिनी।"',
    mantraCaption: '— प्राचीन वैदिक मंत्र',
    heroSubtitle: 'पवित्र भेंट',
    heroTitle: 'श्री नारायणी वेदिका',
    heroTitleItalic: 'शक्ति धूप कप',
    heroDesc: 'प्राचीन वनस्पति विज्ञान की परिवर्तनकारी शक्ति का अनुभव करें। आपके मंदिर में विजय और सुरक्षा का संचार करने के लिए 108 पवित्र जड़ी-बूटियों से हस्तनिर्मित।',
    shopTheRitual: 'अनुष्ठान खरीदें',
    ourStory: 'हमारी कहानी',
    storyTitle: 'पवित्र वृक्ष की कहानी',
    storyIntro: 'स्था. प्राचीन ज्ञान',
    storyDesc1: 'किंवदंती है कि शमी वृक्ष (प्रोसोपिस सिनेरिया) ने पांडवों को उनके अज्ञातवास के दौरान आश्रय दिया था। श्री नारायणी वेदिका में, हम लचीलापन, विजय और सुरक्षा के इस स्थायी प्रतीक का जश्न मनाते हैं। हमारा मिशन इस पवित्र वंश के सार को आधुनिक घरों में लाना है।',
    storyDesc2: 'हमारा हर उत्पाद पवित्रता की शांत विलासिता का प्रमाण है—गुणवत्ता में अटूट, विरासत में गहरा और अपनी सुगंध में दिव्य।',
    storyButton: 'हमारा पूरा दर्शन पढ़ें',
    collectionTitle: 'हमारा पवित्र संग्रह',
    collectionSubtitle: 'विरासत से भरपूर आध्यात्मिक आवश्यकताओं का चयन।',
    newsletterTitle: 'हमारे पवित्र सर्कल में शामिल हों',
    newsletterSubtitle: 'साप्ताहिक ध्यान और सीमित संस्करण आध्यात्मिक संग्रह तक जल्दी पहुंच प्राप्त करें।',
    emailPlaceholder: 'ritual@sacred.com',
    subscribe: 'सब्सक्राइब करें',
    footerConcept: 'पवित्रता की शांत विलासिता।',
    allProducts: 'सभी उत्पाद',
    shaktiDhoopCat: 'शक्ति धूप',
    premiumAgarbattiCat: 'प्रीमियम अगरबत्ती',
    traditionalHavanCat: 'हवन सामग्री',
    featuredTag: 'विशेष',
    addToCart: 'कार्ट में जोड़ें',
    buyNow: 'अभी खरीदें',
    selectSize: 'आकार चुनें',
    priceSymbol: '₹',
    quantity: 'मात्रा',
    packOf12: '12 कप का पैक',
    naturalIngredients: '100% प्राकृतिक सामग्री',
    ritualReady: 'शुद्धिकरण अनुष्ठान हेतु तैयार',
    burnDuration: '45-मिनट जलने की अवधि',
    authenticHeritage: 'प्रामाणिक विरासत मिश्रण',
    ritualTitle: 'अनुष्ठान का अनुभव',
    ritualSubtitle: 'प्राचीन आध्यात्मिक स्वच्छता के संरचित प्रदर्शन के माध्यम से इंद्रियों को जागृत करें और आत्मा को शुद्ध करें।',
    ritualStep1Title: '01. शुद्धिकरण',
    ritualStep1Desc: 'वेदिका शक्ति कप को एक गैर-ज्वलनशील बर्नर में रखें। इसके किनारे को तब तक जलाएं जब तक वह लाल न हो जाए, फिर पवित्र धुआं निकलने देने के लिए लौ को फूंक मारकर बुझा दें।',
    ritualStep2Title: '02. आह्वान',
    ritualStep2Desc: 'जैसे ही धुआं कमरे में भर जाए, अपने घर और संकल्पों पर विजय और सुरक्षा पाने के लिए शमी मंत्र का पाठ करें।',
    ritualStep3Title: '03. प्रसार',
    ritualStep3Desc: 'बर्नर को अपने घर के हर कोने में घड़ी की दिशा (clockwise) में घुमाएं। पवित्र सामग्री नकारात्मक ऊर्जा को निष्प्रभावी कर देगी और शांति की एक सुखद सुगंध छोड़ देगी।',
    sacredIngredientsTitle: 'पवित्र सामग्री',
    ingredient1Title: 'गुग्गुल और लोबान',
    ingredient1Desc: 'जंगलों के हृदय से प्राप्त, ये राल अपने शक्तिशाली रोगाणुरोधी गुणों और वायु-शोधन गुणों के लिए जाने जाते हैं।',
    ingredient2Title: 'देशी गाय का गोबर',
    ingredient2Desc: 'प्रत्येक कप का आधार शुद्ध देशी गाय का गोबर है, जो वैदिक हवन में एक मौलिक तत्व है और पर्यावरणीय कंपन को संतुलित करने में सहायक माना जाता है।',
    ingredient3Title: 'आयुर्वेदिक जड़ी-बूटियाँ',
    ingredient3Desc: '12 दुर्लभ जड़ी-बूटियों का एक विशेष मिश्रण जो ध्यान के दौरान तनाव कम करने, मानसिक स्पष्टता और एकाग्रता में मदद करता है।',
    victorySlogan: 'शमी शमयते पापं, शमी शत्रुविनाशिनी। विजयाय नमः ||',
    shamiVictoryBox: 'शमी विजय बॉक्स',
    shamiVictoryDesc: 'हमारी बेहतरीन धूप और सामग्री का एक क्यूरेटेड संग्रह, एक टिकाऊ हस्तशिल्प लकड़ी की तिजोरी में पैक किया गया। आध्यात्मिक उत्थान के लिए सर्वोत्तम उपहार।',
    bespokeExperience: 'विशेष अनुभव',
    heritageSeries: 'विरासत श्रृंखला',
    artisanalDhoopbatti: 'कलात्मक धूपबत्ती',
  }
};
export const initialOrders = [
  {
    id: "CN-9824",
    customerName: "Rajesh Kumar",
    address: "Bungalow 4, Malabar Hill",
    city: "Mumbai",
    pincode: "400006",
    phone: "9876543210",
    date: "2026-05-28",
    amount: 2450,
    items: [{ productName: "Pure Sandalwood Classic", productNameHi: "शुद्ध चंदन क्लासिक", quantity: 3, price: 450 }, { productName: "Shree Narayani Vedica Shakti Dhoop Cup", productNameHi: "श्री नारायणी वेदिका शक्ति धूप कप", quantity: 1, price: 599 }],
    status: "Shipped",
    statusHi: "भेज दिया गया"
  },
  {
    id: "CN-9825",
    customerName: "Ananya Sharma",
    address: "C-12, Vasant Vihar",
    city: "New Delhi",
    pincode: "110057",
    phone: "9812345678",
    date: "2026-05-29",
    amount: 8900,
    items: [{ productName: "Agnihotra Sacred Blend", productNameHi: "अग्निहोत्र पावन मिश्रण", quantity: 10, price: 890 }],
    status: "Processing",
    statusHi: "प्रक्रियाधीन"
  },
  {
    id: "CN-9826",
    customerName: "Vikram Singh",
    address: "Naila Bagh Palace",
    city: "Jaipur",
    pincode: "302004",
    phone: "9611223344",
    date: "2026-05-29",
    amount: 1198,
    items: [{ productName: "Shree Narayani Vedica Shakti Dhoop Cup", productNameHi: "श्री नारायणी वेदिका शक्ति धूप कप", quantity: 2, price: 599 }],
    status: "Delivered",
    statusHi: "वितरित"
  }
];
